//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotivationMinders.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MMEntitiesContext : DbContext
    {
        public MMEntitiesContext()
            : base("name=MMEntitiesContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        //This is for pre-made charms to sell on the main page
        public virtual DbSet<charm> charms { get; set; }

        public virtual DbSet<ProductImage> ProductImages { get; set; }

        public virtual DbSet<product> products { get; set; }

        public virtual DbSet<ProductTag> ProductTags { get; set; }

        public virtual DbSet<Role> Roles { get; set; }

        //Not currently in use
        public virtual DbSet<Supplier> Suppliers { get; set; }

        public virtual DbSet<SystemUser> SystemUsers { get; set; }

        public virtual DbSet<BlogPost> BlogPosts { get; set; }
    }
}
