//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotivationMinders.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public int productImageID { get; set; }
        public int productID { get; set; }
        public string filename { get; set; }
        public bool featured { get; set; }
    
        public virtual product product { get; set; }
    }
}
