//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotivationMinders
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int supplierID { get; set; }
        public string supplierName { get; set; }
        public string contactNumber { get; set; }
        public string contactName { get; set; }
        public string location { get; set; }
        public string postalCode { get; set; }
    }
}
